config/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView
from django.views import defaults as default_views



urlpatterns = [
    url(r'^$', TemplateView.as_view(template_name='pages/home.html'), name="home"),
    url(r'^about/$', TemplateView.as_view(template_name='pages/about.html'), name="about"),

    # Django Admin, use {% url 'admin:index' %}
    url(settings.ADMIN_URL, include(admin.site.urls)),

    # User management
    url(r'^users/', include("locmaster.users.urls", namespace="users")),
    url(r'^accounts/', include('allauth.urls')),

    # Your stuff: custom urls includes go here
    url(r'^unlocode/', include('unlocode.urls', namespace="unlocode")),
    url(r'^mylocation/', include('mylocation.urls', namespace="mylocation")),


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        url(r'^400/$', default_views.bad_request, kwargs={'exception': Exception("Bad Request!")}),
        url(r'^403/$', default_views.permission_denied, kwargs={'exception': Exception("Permissin Denied")}),
        url(r'^404/$', default_views.page_not_found, kwargs={'exception': Exception("Page not Found")}),
        url(r'^500/$', default_views.server_error),
    ]

unlocode/urls.py
from django.conf.urls import url
from unlocode import views as unlocode_views
from unlocode.viewsets import v0 as v0_views
from unlocode.viewsets import v1 as v1_views


urlpatterns = [
    # URL pattern for the UNLocVersionListView
    url(
        regex=r'^versions/$',
        view=unlocode_views.UnLocVersionList.as_view(),
        name='list',
    ),
    # URL pattern for the UnLocVersionDetailView
    url(
        regex=r'^versions/(?P<pk>[\w\-]+)/$',
        view=unlocode_views.UnLocVersionDetail.as_view(),
        name='detail',
    ),

    url(
        regex=r'^version/create/$',
        view=unlocode_views.UnLocVersionCreate.as_view(),
        name='create'
    ),

    # URL pattern for the UnLocVersionUpdateView
    url(
        regex=r'^version/(?P<pk>[\w\-]+)/$',
        view=unlocode_views.UnLocVersionUpdate.as_view(),
        name='update',
    ),

    # URL pattern for the UnLocVersionDeleteView
    url(
        regex=r'^version/(?P<pk>[\w\-]+)/delete/$',
        view=unlocode_views.UnLocVersionDelete.as_view(),
        name='delete',
    ),
    #                       url(r'^category/(?P<categoryNameSlug>[\w\-]+)/$', views.category, name='category'),
    #                       url(r'^addCategory/$', views.addCategory, name='addCategory'),
    #                       url(r'^category/(?P<categoryNameSlug>[\w\-]+)/addPage/$', views.addPage, name='addPage'),
    #                       url(r'^register/$', views.register, name='register'),
    #                       url(r'^userLogin/$', views.userLogin, name='userLogin'),
    #                       url(r'^restricted/', views.restricted, name='restricted'),
    #                       url(r'^userLogout/', views.userLogout, name='userLogout'),
    #                       url(r'^loggedin/', views.loggedin, name='loggedin'),

    url(
        regex=r'^populate/$',
        view=unlocode_views.Populate.as_view(),
        name='populate',
    ),
    url(
        regex=r'^locodeinfo/$',
        view=unlocode_views.LocodeInfo.as_view(),
        name='populate',
    ),
    url(
        regex=r'^code/(?P<locode>[\w\-]+)/$',
        view=unlocode_views.UnLocodeList.as_view(),
        name='list-code',
    ),
    url(
        regex=r'^code/$',
        view=unlocode_views.UnLocodeSearch.as_view(),
        name='list-search',
    ),

    # URL pattern for the UNLocVersionList V1
    url(
        regex=r'^api/v1/$',
        view=v1_views.LocodeList.as_view(),
        name='v1-list',
    ),
    # URL pattern for the UnLocVersionDetailView V1
    url(
        regex=r'^api/v1/(?P<locode>[\w\-]+)/$',
        view=v1_views.LocodeDetail.as_view(),
        name='v1-detail',
    ),
    # URL pattern for the UnLocVersionList V0
    url(
        regex=r'^api/v0/',
        view=v0_views.gone,
        name='v0-list',
    ),
]

unlocode/models.py
#from django.db import models
from django.contrib.gis.db import models
from django.core.urlresolvers import reverse


class TimeStampedModel(models.Model):
    # Abstract base class model that provides self-updating created and modified fields
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True


class LocVersion(TimeStampedModel):
    version = models.CharField(max_length=6, primary_key=True)
    creator = models.CharField(max_length=100)

    def get_absolute_url(self):
        return reverse("unlocode:detail", kwargs={'pk': self.pk})

    class Meta:
        get_latest_by = "version"
        ordering = ["-version"]

    def __str__(self):
        return self.version


class LocChangeTag(models.Model):
    changetag = models.CharField(max_length=5, unique=True)
    description = models.CharField(max_length=200)

    def __str__(self):
        return self.description


class LocChangeIndicator(models.Model):
    changecode = models.CharField(max_length=1, unique=True)
    description = models.CharField(max_length=200)

    def __str__(self):
        return self.description


class LocFunction(models.Model):
    functioncode = models.CharField(max_length=1)
    description = models.CharField(max_length=200)
    version = models.ForeignKey(LocVersion,
                                on_delete=models.CASCADE,
                                blank=False)

    class Meta:
        unique_together = ("version", "functioncode")
        index_together = ("version", "functioncode")

    def __str__(self):
        return self.description


class LocStatus(models.Model):
    statuscode = models.CharField(max_length=2)
    description = models.CharField(max_length=200)
    version = models.ForeignKey(LocVersion,
                                on_delete=models.CASCADE,
                                blank=False)

    class Meta:
        unique_together = ("version", "statuscode")
        index_together = ("version", "statuscode")
        verbose_name_plural = "LocStatus"

    def __str__(self):
        return self.description


class Country(models.Model):
    name = models.CharField(max_length=200)
    alpha2code = models.CharField(max_length=2, unique=True)
    alpha3code = models.CharField(max_length=3, unique=True)
    numericcode = models.CharField(max_length=3, unique=True)
    latitudeavg = models.FloatField()
    longitudeavg = models.FloatField()

    def __str__(self):
        return self.name


class SubDivision(models.Model):
    name = models.CharField(max_length=100)
    level1 = models.CharField(max_length=8)
    level2 = models.CharField(max_length=8)
    shortcode = models.CharField(max_length=5)
    alpha2code = models.CharField(max_length=2)

    def __str__(self):
        return self.name


class LocCountry(models.Model):
    alpha2code = models.CharField(max_length=2)
    name = models.CharField(max_length=200)
    version = models.ForeignKey(LocVersion,
                                on_delete=models.CASCADE,
                                blank=False)

    class Meta:
        unique_together = ("version", "alpha2code")
        index_together = ("version", "alpha2code")

    def __str__(self):
        return self.name


class LocSubdivision(models.Model):
    alpha2code = models.ForeignKey(LocCountry, on_delete=models.CASCADE)
    shortcode = models.CharField(max_length=5)
    name = models.CharField(max_length=100)
    version = models.ForeignKey(LocVersion,
                                on_delete=models.CASCADE,
                                blank=False)

    class Meta:
        unique_together = ("version", "alpha2code", "shortcode")
        index_together = ("version", "alpha2code", "shortcode")

    def __str__(self):
        return self.name


class Locode(models.Model):
    # as described here: http://www.unece.org/fileadmin/DAM/cefact/locode/Service/LocodeColumn.htm

    locchangeindicator = models.ForeignKey(LocChangeIndicator, on_delete=models.SET_NULL, blank=True, null=True)
    locstatus = models.ForeignKey(LocStatus, on_delete=models.SET_NULL, blank=True, null=True)
    locodecountry = models.ForeignKey(LocCountry, on_delete=models.CASCADE)
    locodeplace = models.CharField(max_length=3)
    locname = models.CharField(max_length=100, db_index=True)
    locnamewodia = models.CharField(max_length=100, db_index=True)
    locsubdivision = models.ForeignKey(LocSubdivision, on_delete=models.CASCADE, blank=True, null=True)
    locfunction = models.CharField(max_length=8)
    locdate = models.CharField(max_length=4)
    lociata = models.CharField(max_length=3)
    locoordinates = models.CharField(max_length=12)
    locremarks = models.CharField(max_length=100)
    locode = models.CharField(max_length=5, db_index=True)
    version = models.ForeignKey(LocVersion,
                                on_delete=models.CASCADE,
                                blank=False)

    class Meta:
        unique_together = ("version", "locode")
        index_together = ("version", "locode")

    def save(self, *args, **kwargs):
        self.locode = self.locodecountry.alpha2code + self.locodeplace
        super(Locode, self).save(*args, **kwargs)

    def __str__(self):
        return self.locname

unlocode/forms.py
from django import forms

unlocode/views.py
from django.shortcuts import render
from django.http import HttpResponse
# Create your views here.
from django.contrib import messages
from braces.views import LoginRequiredMixin
from django.views.generic import DetailView, ListView, UpdateView, CreateView, DeleteView, TemplateView
from django.core.urlresolvers import reverse_lazy
from unlocode.models import LocVersion, Locode
from unlocode.initializedata import populateInitial
from unlocode.csvimport import check_version_dir
from unlocode.tasks import importVersion, orderPizza
from django.db.models import Q
import os

class UnLocVersionMixin(object):
    model = LocVersion
    fields = ['version']

    @property
    def success_msg(self):
        return NotImplemented

    def form_valid(self, form):
        messages.info(self.request, self.success_msg)
        return super(UnLocVersionMixin, self).form_valid(form)


class UnLocVersionDetail(LoginRequiredMixin, DetailView):
    model = LocVersion
    context_object_name = 'version'
    def get_context_data(self, **kwargs):
        context = super(UnLocVersionDetail,self).get_context_data(**kwargs)
        context["files"]=check_version_dir(str(self.kwargs.get('pk')))
        context['complete']=not(False in dict(context["files"]).values())
        return context

class UnLocodeSearch(LoginRequiredMixin, ListView):
    model = Locode
    context_object_name = "unlocode"
    queryset = Locode.objects.none()
    template_name = 'unlocode/locode_search.html'

    def get_queryset(self):
        queryset = super(UnLocodeSearch, self).get_queryset()

        q = self.request.GET.get("q")
        if q:

            return Locode.objects.filter(
                Q(locode__iexact=q)|
                Q(locname__istartswith=q) |
                Q(locnamewodia__istartswith=q)).order_by('locode', 'version').distinct('locode')

        return queryset



class UnLocodeList(LoginRequiredMixin, ListView):
    model = Locode
    context_object_name = 'unlocode'
    allow_empty = False

    def get_queryset(self):
        return Locode.objects.filter(locode=self.kwargs.get('locode')).order_by("version")

    def get_context_data(self, **kwargs):
        context = super(UnLocodeList, self).get_context_data(**kwargs)
        context["thelocode"] = self.kwargs.get('locode')
        return context


class UnLocVersionList(LoginRequiredMixin, ListView):
    model = LocVersion
    context_object_name = 'version_list'
    queryset = LocVersion.objects.order_by("-version")



class UnLocVersionCreate(LoginRequiredMixin, UnLocVersionMixin, CreateView):
    success_msg = "Created"

    def form_valid(self, form):
        form.instance.creator = self.request.user.username
        return super(UnLocVersionCreate, self).form_valid(form)


class UnLocVersionUpdate(LoginRequiredMixin, UnLocVersionMixin, UpdateView):
    success_msg = "Updated"

    def post(self, request, *args, **kwargs):
        if 'load' in request.POST:
            importVersion.delay(str(self.kwargs.get('pk')))
            messages.info(request, "Background Job Started, come back to see if it is done")
            #messages.info(request, importUNLOCODE(str(self.kwargs.get('pk'))))
            return super(UnLocVersionUpdate, self).get(request, *args, **kwargs)
        else:
            return super(UnLocVersionUpdate, self).post(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(UnLocVersionUpdate,self).get_context_data(**kwargs)
        context["files"]=check_version_dir(str(self.kwargs.get('pk')))
        context['complete']=not(False in dict(context["files"]).values())
        return context

    def form_valid(self, form):
        form.instance.creator = self.request.user.username
        return super(UnLocVersionUpdate, self).form_valid(form)


class UnLocVersionDelete(LoginRequiredMixin, UnLocVersionMixin, DeleteView):
    success_msg = "Deleted"
    success_url = reverse_lazy('unlocode:list')


class Populate(TemplateView):

    template_name = 'unlocode/populate.html'

    def post(self, request, *args, **kwargs):
        context = self.get_context_data()
        messages.info(request, populateInitial())
        return super(TemplateView, self).render_to_response(context)


class LocodeInfo(TemplateView):

    template_name = 'unlocode/locode_info.html'
    allow_empty = False

    def get_context_data(self, **kwargs):
        context = super(LocodeInfo,self).get_context_data(**kwargs)
        context["info"] = os.getcwd() + "/unlocode/data/versions/TEST-1"
        return context

    def post(self, request, *args, **kwargs):
            orderPizza.delay("Napoli con extra Scharf")
            return super(LocodeInfo, self).get(request, *args, **kwargs)

unlocode/templates/unlocode/locode_info.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% load static %}{% load i18n %}
{% block title %}Locode Info{% endblock %}

{% block content %}

    <h2>Info:</h2>

    <strong> {{ info }} </strong>
        <form action="" method="post">
        {% csrf_token %}
        {{ form|crispy }}
                    <input type="submit" class="btn btn-secondary" name = "load" value="Load Data" />
        </form>
{% endblock content %}

unlocode/templates/unlocode/locode_list.html
{% extends "base.html" %}

{% load static %}{% load i18n %}
{% block title %}Versions{% endblock %}

{% block content %}

    <br>
    <h2>{{ thelocode }} </h2>
    <br>
        <div class="table-responsive">
        <table class="table table-striped">
            <thead>
                <th>Chg</th>
                <th>Country</th>
                <th>Place</th>
                <th>Name</th>
                <th>Name(-dia)</th>
                <th>Subdiv</th>
                <th>Function</th>
                <th>Date</th>
                <th>IATA</th>
                <th>Coordinates</th>
                <th>Remarks</th>
                <th>Status</th>
                <th>Version</th>
            </thead>
            <tbody>
              {% for location in unlocode %}
                <tr>
                    <td>{{ location.locchangeindicator|default_if_none:" " }}</td>
                    <td>{{ location.locodecountry }}</td>
                    <td>{{ location.locodeplace }}</td>
                    <td>{{ location.locname }}</td>
                    <td>{{ location.locnamewodia }}</td>
                    <td>{{ location.locsubdivision|default_if_none:" " }}</td>
                    <td>{{ location.locfunction }}</td>
                    <td>{{ location.locdate }}</td>
                    <td>{{ location.lociata }}</td>
                    <td>{{ location.locoordinates }}</td>
                    <td>{{ location.locremarks }}</td>
                    <td>{{ location.locstatus|default_if_none:" " }}</td>
                    <td>{{ location.version }}</td>
                </tr>
              {% endfor %}
            </tbody>
          </table>
        </div>
    <br>

{% endblock content %}

unlocode/templates/unlocode/locode_search.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% load static %}{% load i18n %}
{% block title %}Versions{% endblock %}

{% block content %}
    <br>
    <form action="" method="GET">
    {{ form|crispy }}
        <div class="input-group">
            <input type="text" class="form-control" placeholder="Search for..." name="q">
            <span class="input-group-btn">
            <button class="btn btn-primary" type="button">Go!</button>
      </span>
    </div>
    </form>

    <br>
        <div class="table-responsive">
        <table class="table table-striped">
            <thead>
                <th>Chg</th>
                <th>Country</th>
                <th>Place</th>
                <th>Name</th>
                <th>Name(-dia)</th>
                <th>Subdiv</th>
                <th>Function</th>
                <th>Date</th>
                <th>IATA</th>
                <th>Coordinates</th>
                <th>Remarks</th>
                <th>Status</th>
                <th>Version</th>
                <th>Action</th>
            </thead>
            <tbody>
              {% for location in unlocode %}
                <tr>
                    <td>{{ location.locchangeindicator|default_if_none:""  }}</td>
                    <td>{{ location.locodecountry }}</td>
                    <td>{{ location.locodeplace }}</td>
                    <td>{{ location.locname }}</td>
                    <td>{{ location.locnamewodia }}</td>
                    <td>{{ location.locsubdivision|default_if_none:""  }}</td>
                    <td>{{ location.locfunction }}</td>
                    <td>{{ location.locdate }}</td>
                    <td>{{ location.lociata }}</td>
                    <td>{{ location.locoordinates }}</td>
                    <td>{{ location.locremarks }}</td>
                    <td>{{ location.locstatus|default_if_none:"" }}</td>
                    <td>{{ location.version }}</td>
                    <td><a href={% url 'unlocode:list-code' location.locode %} class="btn btn-secondary btn-sm"><i class="fa fa-info" ></i></a></td>
                </tr>
              {% endfor %}
            </tbody>
          </table>
        </div>
    <br>

{% endblock content %}

unlocode/templates/unlocode/locversion_confirm_delete.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% load static %}{% load i18n %}
{% block title %}Delete Version ?{% endblock %}

{% block content %}
    <br>
    <form action="" method="post">{% csrf_token %}
    {{ form|crispy }}
        <p>Are you sure you want to delete "{{ object }}"?</p>
        <input type="submit" class="btn btn-danger" value="Confirm" />
     <a href={% url 'unlocode:list' %} class="btn btn-secondary btn-large" role="button" >Cancel</a>
    </form>

{% endblock content %}

unlocode/templates/unlocode/locversion_detail.html
{% extends "base.html" %}

{% load static %}{% load i18n %}
{% block title %}Versions{% endblock %}

{% block content %}

    <br>
    <h2>{{ version.version }} </h2>
    Created on: {{ version.created }} <br>
    Modified on: {{ version.modified }} <br>
    Edited by: {{ version.creator }}
    <br>
          <table>
                <th>File Name</th>
                <th>Status</th>
            {% for file in files %}
                <tr>
                    <td>{{ file.0 }}</td>
                    {% if file.1 %}
                        <td class="text-success"><i class="fa fa-check-circle"></i></td>
                        {% else %}
                        <td class="text-danger"><i class="fa fa-times-circle"></i></td>
                    {% endif %}
                </tr>
            {% endfor %}
          </table>
    <br>

        <a href={% url 'unlocode:update' version.version %} class="btn btn-primary btn-large" role="button" >Change</a>
        <a href={% url 'unlocode:delete' version.version %} class="btn btn-danger btn-large" role="button" >Delete</a>


{% endblock content %}

unlocode/templates/unlocode/locversion_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% load static %}{% load i18n %}
{% block title %}Versions{% endblock %}

{% block content %}
    <br>
    <form action="" method="post">
        {% csrf_token %}
        {{ form|crispy }}
        {% if files %}
                    <br>
            <table>
                <th>File Name</th>
                <th>Status</th>
            {% for file in files %}
                <tr>
                    <td>{{ file.0 }}</td>
                    {% if file.1 %}
                        <td class="text-success"><i class="fa fa-check-circle"></i></td>
                        {% else %}
                        <td class="text-danger"><i class="fa fa-times-circle"></i></td>
                    {% endif %}
                </tr>
            {% endfor %}
          </table>
        <br>

        {% endif %}

        {% if object.version %}
            <input type="submit" class="btn btn-primary" name = "save" value="Save" />

            {% if complete  %}
                <input type="submit" class="btn btn-secondary" name = "load" value="Load Data" />
            {% else %}
                <input disabled type="submit" class="btn btn-secondary" name = "load" value="Load Data" />
            {% endif %}

        {% else %}
            <input type="submit" class="btn btn-primary" name = "save" value="Add" />
        {% endif %}

        <a href={% url 'unlocode:list' %} class="btn btn-secondary btn-large" role="button" >Cancel</a>
</form>


{% endblock content %}

unlocode/templates/unlocode/locversion_list.html
{% extends "base.html" %}
{% load static %}{% load i18n %}
{% block title %}Versions{% endblock %}

{% block content %}
    <br>
    <div class="container">
        <h2>Versions</h2>
    </div>

    <div class="table-container">
        <table class="table table-hover">
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Timestamp</th>
                    <th>Creator</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody>
                {% for locversion in version_list %}
                    <tr>
                        <th scope="row"><a href={{ locversion.get_absolute_url }}> {{ locversion.version }} </a> </th>
                        <td> {% if locversion.modified %} {{ locversion.modified }} {% else %} {{ locversion.created }}{% endif %}</td>
                        <td>{{ locversion.creator }}</td>
                        <td> <a href={% url 'unlocode:update' locversion.version %} class="btn btn-success btn-sm"><i class="fa fa-pencil" ></i></a>&nbsp; <a href={% url 'unlocode:delete' locversion.version %} class="btn btn-danger btn-sm"> <i class="fa fa-trash"></i></a></td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
         <a href={% url 'unlocode:create' %} class="btn btn-primary btn-large" role="button" >Add new</a>
    </div>
{% endblock content %}

unlocode/templates/unlocode/populate.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% load static %}{% load i18n %}

{% block title %}Populate Database{% endblock %}

{% block content %}
    <form action="" method="post">{% csrf_token %}
        <br>
        {{ form|crispy }}
        <input type="submit" class="btn btn-primary" value="Start Import" />
    </form>
{% endblock content %}

unlocode/templates/unlocode/version_list.html
{% extends "base.html" %}
{% load static %}{% load i18n %}
{% block title %}Versions{% endblock %}

{% block content %}
    <div class="container">
        <h2>Version New</h2>
    </div>

    <div class="table-container">
        <table class="table table-hover">
            <thead>
                <th>Name</th>
                <th class="hidden-xs">Created by</th>
                <th class="hidden-xs">Timestamp</th>
                <th>Files</th>
            </thead>
            <tbody>
                {% for locversion in version_list %}
                    <tr>
                        <td><a href=/{{ locversion.version }}/>{{ locversion.version }}</a></td>
                        <td class="hidden-xs">TBD</td>
                        <td class="hidden-xs">OCT 21 2015 PM 07:28</td>
                        <td>Yes</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock content %}