config/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView
from django.views import defaults as default_views



urlpatterns = [
    url(r'^$', TemplateView.as_view(template_name='pages/home.html'), name="home"),
    url(r'^about/$', TemplateView.as_view(template_name='pages/about.html'), name="about"),

    # Django Admin, use {% url 'admin:index' %}
    url(settings.ADMIN_URL, include(admin.site.urls)),

    # User management
    url(r'^users/', include("locmaster.users.urls", namespace="users")),
    url(r'^accounts/', include('allauth.urls')),

    # Your stuff: custom urls includes go here
    url(r'^unlocode/', include('unlocode.urls', namespace="unlocode")),
    url(r'^mylocation/', include('mylocation.urls', namespace="mylocation")),


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        url(r'^400/$', default_views.bad_request, kwargs={'exception': Exception("Bad Request!")}),
        url(r'^403/$', default_views.permission_denied, kwargs={'exception': Exception("Permissin Denied")}),
        url(r'^404/$', default_views.page_not_found, kwargs={'exception': Exception("Page not Found")}),
        url(r'^500/$', default_views.server_error),
    ]

locmaster/users/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.conf.urls import url

from . import views

urlpatterns = [
    # URL pattern for the UserListView
    url(
        regex=r'^$',
        view=views.UserListView.as_view(),
        name='list'
    ),

    # URL pattern for the UserRedirectView
    url(
        regex=r'^~redirect/$',
        view=views.UserRedirectView.as_view(),
        name='redirect'
    ),

    # URL pattern for the UserDetailView
    url(
        regex=r'^(?P<username>[\w.@+-]+)/$',
        view=views.UserDetailView.as_view(),
        name='detail'
    ),

    # URL pattern for the UserUpdateView
    url(
        regex=r'^~update/$',
        view=views.UserUpdateView.as_view(),
        name='update'
    ),
]

mylocation/urls.py
from django.conf.urls import url
from mylocation import views as mylocation_views
from django.views.generic import TemplateView

urlpatterns = [
    # URL pattern for the UNLocVersionListView
    url(
        regex=r'^welcome/$',
        view=TemplateView.as_view(template_name='mylocation/welcome.html'),
        name='welcome',
    ),
    # URL pattern for the FunctionDetailView
    # URL pattern for the FunctionCreateView
    url(
        regex=r'^function/create/$',
        view=mylocation_views.FunctionCreate.as_view(),
        name='function-create',
    ),
    url(
        regex=r'^function/(?P<pk>[\w\-]+)/$',
        view=mylocation_views.FunctionDetail.as_view(),
        name='function-detail',
    ),
    # URL pattern for the FunctionUpdateView
    url(
        regex=r'^function/(?P<pk>[\w\-]+)/update/$',
        view=mylocation_views.FunctionUpdate.as_view(),
        name='function-update',
    ),
    # URL pattern for the FunctionUpdateView
    url(
        regex=r'^function/(?P<pk>[\w\-]+)/delete/$',
        view=mylocation_views.FunctionDelete.as_view(),
        name='function-delete',
    ),
    # URL pattern for the FunctionListview
    url(
        regex=r'^function/$',
        view=mylocation_views.FunctionList.as_view(),
        name='function-list',
    ),
]

unlocode/urls.py
from django.conf.urls import url
from unlocode import views as unlocode_views
from unlocode.viewsets import v0 as v0_views
from unlocode.viewsets import v1 as v1_views


urlpatterns = [
    # URL pattern for the UNLocVersionListView
    url(
        regex=r'^versions/$',
        view=unlocode_views.UnLocVersionList.as_view(),
        name='list',
    ),
    # URL pattern for the UnLocVersionDetailView
    url(
        regex=r'^versions/(?P<pk>[\w\-]+)/$',
        view=unlocode_views.UnLocVersionDetail.as_view(),
        name='detail',
    ),

    url(
        regex=r'^version/create/$',
        view=unlocode_views.UnLocVersionCreate.as_view(),
        name='create'
    ),

    # URL pattern for the UnLocVersionUpdateView
    url(
        regex=r'^version/(?P<pk>[\w\-]+)/$',
        view=unlocode_views.UnLocVersionUpdate.as_view(),
        name='update',
    ),

    # URL pattern for the UnLocVersionDeleteView
    url(
        regex=r'^version/(?P<pk>[\w\-]+)/delete/$',
        view=unlocode_views.UnLocVersionDelete.as_view(),
        name='delete',
    ),
    #                       url(r'^category/(?P<categoryNameSlug>[\w\-]+)/$', views.category, name='category'),
    #                       url(r'^addCategory/$', views.addCategory, name='addCategory'),
    #                       url(r'^category/(?P<categoryNameSlug>[\w\-]+)/addPage/$', views.addPage, name='addPage'),
    #                       url(r'^register/$', views.register, name='register'),
    #                       url(r'^userLogin/$', views.userLogin, name='userLogin'),
    #                       url(r'^restricted/', views.restricted, name='restricted'),
    #                       url(r'^userLogout/', views.userLogout, name='userLogout'),
    #                       url(r'^loggedin/', views.loggedin, name='loggedin'),

    url(
        regex=r'^populate/$',
        view=unlocode_views.Populate.as_view(),
        name='populate',
    ),
    url(
        regex=r'^locodeinfo/$',
        view=unlocode_views.LocodeInfo.as_view(),
        name='populate',
    ),
    url(
        regex=r'^code/(?P<locode>[\w\-]+)/$',
        view=unlocode_views.UnLocodeList.as_view(),
        name='list-code',
    ),
    url(
        regex=r'^code/$',
        view=unlocode_views.UnLocodeSearch.as_view(),
        name='list-search',
    ),

    # URL pattern for the UNLocVersionList V1
    url(
        regex=r'^api/v1/$',
        view=v1_views.LocodeList.as_view(),
        name='v1-list',
    ),
    # URL pattern for the UnLocVersionDetailView V1
    url(
        regex=r'^api/v1/(?P<locode>[\w\-]+)/$',
        view=v1_views.LocodeDetail.as_view(),
        name='v1-detail',
    ),
    # URL pattern for the UnLocVersionList V0
    url(
        regex=r'^api/v0/',
        view=v0_views.gone,
        name='v0-list',
    ),
]

locmaster/users/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals, absolute_import

from django.contrib.auth.models import AbstractUser
from django.core.urlresolvers import reverse
from django.db import models
from django.utils.encoding import python_2_unicode_compatible
from django.utils.translation import ugettext_lazy as _


@python_2_unicode_compatible
class User(AbstractUser):

    # First Name and Last Name do not cover name patterns
    # around the globe.
    name = models.CharField(_("Name of User"), blank=True, max_length=255)

    def __str__(self):
        return self.username

    def get_absolute_url(self):
        return reverse('users:detail', kwargs={'username': self.username})

locmaster/users/views.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.core.urlresolvers import reverse
from django.views.generic import DetailView, ListView, RedirectView, UpdateView

from braces.views import LoginRequiredMixin

from .models import User


class UserDetailView(LoginRequiredMixin, DetailView):
    model = User
    # These next two lines tell the view to index lookups by username
    slug_field = "username"
    slug_url_kwarg = "username"


class UserRedirectView(LoginRequiredMixin, RedirectView):
    permanent = False

    def get_redirect_url(self):
        return reverse("users:detail",
                       kwargs={"username": self.request.user.username})


class UserUpdateView(LoginRequiredMixin, UpdateView):

    fields = ['name', ]

    # we already imported User in the view code above, remember?
    model = User

    # send the user back to their own page after a successful update
    def get_success_url(self):
        return reverse("users:detail",
                       kwargs={"username": self.request.user.username})

    def get_object(self):
        # Only get the User record for the user making the request
        return User.objects.get(username=self.request.user.username)


class UserListView(LoginRequiredMixin, ListView):
    model = User
    # These next two lines tell the view to index lookups by username
    slug_field = "username"
    slug_url_kwarg = "username"

locmaster/templates/base.html
{% load staticfiles i18n %}<!DOCTYPE html>
<html lang="en" ng-app>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>{% block title %}locmaster{% endblock title %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="https://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

    {% block css %}
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdn.rawgit.com/twbs/bootstrap/v4-dev/dist/css/bootstrap.css">

    <!-- Your stuff: Third-party css libraries go here -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">

    <!-- This file store project specific CSS -->
    <link href="{% static 'css/project.css' %}" rel="stylesheet">
    {% endblock %}

    {% block angular %}
    <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.4.8/angular.min.js"></script>
    {% endblock %}

  </head>

  <body>

    <div class="m-b">
      <nav class="navbar navbar-dark navbar-static-top bg-inverse">
        <div class="container">
          <a class="navbar-brand" href="/">Location Master</a>
          <button type="button" class="navbar-toggler hidden-sm-up pull-xs-right" data-toggle="collapse" data-target="#bs-navbar-collapse-1">
            &#9776;
          </button>

          <!-- Collect the nav links, forms, and other content for toggling -->
          <div class="collapse navbar-toggleable-xs" id="bs-navbar-collapse-1">
            <ul class="nav navbar-nav">
              <li class="nav-item">
                <a class="nav-link" href="{% url 'home' %}">Home</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'about' %}">About</a>
              </li>
                {% if request.user.is_authenticated %}
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">UN Locode</a>
                        <div class="dropdown-menu">
                            <a class="dropdown-item" href="{% url 'unlocode:list' %}">{% trans "Version" %}</a>
                            <a class="dropdown-item" href="{% url 'unlocode:list-search' %}">{% trans "Search" %}</a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="{% url 'unlocode:populate' %}">{% trans "Populate" %}</a>
                        </div>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">My Location</a>
                        <div class="dropdown-menu">
                            <a class="dropdown-item" href="{% url 'mylocation:welcome' %}">{% trans "Welcome" %}</a>
                            <a class="dropdown-item" href="{% url 'mylocation:function-list' %}">{% trans "Functions" %}</a>
                        </div>
                    </li>
                {% endif %}
            </ul>

            <ul class="nav navbar-nav pull-xs-right">
              {% if request.user.is_authenticated %}
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'users:detail' request.user.username  %}">{% trans "My Profile" %}</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'account_logout' %}">{% trans "Logout" %}</a>
                </li>
              {% else %}
                <li class="nav-item">
                  <a id="sign-up-link" class="nav-link" href="{% url 'account_signup' %}">{% trans "Sign Up" %}</a>
                </li>
                <li class="nav-item">
                  <a id="log-in-link" class="nav-link" href="{% url 'account_login' %}">{% trans "Log In" %}</a>
                </li>
              {% endif %}
            </ul>
          </div>
        </div>
      </nav>
    </div>

    <div class="container">

      {% if messages %}
          {% for message in messages %}
              <div class="alert {% if message.tags %}alert-{{ message.tags }}{% endif %}">{{ message }}</div>
          {% endfor %}
      {% endif %}

      {% block content %}
        <p>Use this document as a way to quick start any new project.</p>
      {% endblock content %}

    </div> <!-- /container -->

    {% block modal %}{% endblock modal %}

    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    {% block javascript %}
      <!-- Latest JQuery -->
      <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>

      <!-- Tether - a requirement for Bootstrap tooltips -->
      <script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.1.1/js/tether.min.js"></script>

      <!-- Latest compiled and minified JavaScript -->
      <script src="https://cdn.rawgit.com/twbs/bootstrap/v4-dev/dist/js/bootstrap.js"></script>

      <!-- Your stuff: Third-party javascript libraries go here -->

      <!-- place project specific Javascript in this file -->
      <script src="{% static 'js/project.js' %}"></script>
    {% endblock javascript %}
  </body>
</html>